version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/uniplato
    ports:
      - '4000:4000'
      - '9229:9229'
    volumes:
      - ./:/app/
    depends_on:
      mysql:
        condition: service_healthy # Wait for MySQL to be healthy
    env_file:
      - .env
    restart: on-failure
    networks:
      - uniplato_network
    # command: ['wait-for-it.sh', 'mysql:3306', '--', 'pnpm', 'run', 'start:dev']

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uniplato
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_GRANT_PRIVILEGES: 'Y'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - uniplato_network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 5s
      retries: 10

volumes:
  mysql_data:

networks:
  uniplato_network:
    driver: bridge
